# Airframe Propulsion Parameters
# Motor types: 0 No motor, 1 generic Engine

nMotors: 2
motor1/rotationDir: -1.0

motor1/motorType: 3
motor1/Kv: 14.667 # in RPS/V
motor1/Rm: 0.307 # in Ohms
motor1/I0: 0.6 # in Amperes

motor1/RadPSLimits: [0.01, 1600.0]
motor1/engInertia: 0.008 # in kg*m^3

prop1/propDiam: 1.3 # in m
prop1/nCoeffPoly/polyType: 0
prop1/nCoeffPoly/polyNo: 4
prop1/nCoeffPoly/coeffs: [0.0, -1.25, 19.73, -45.21, 28.81]
prop1/powerPoly/polyType: 0
prop1/powerPoly/polyNo: 3
prop1/powerPoly/coeffs: [0.0487, -0.1187, 0.1787, -0.1314]


motor2/rotationDir: 1.0

motor2/motorType: 3
motor2/Kv: 14.667 # in RPS/V
motor2/Rm: 0.307 # in Ohms
motor2/I0: 0.6 # in Amperes

motor2/RadPSLimits: [0.01, 1600.0]
motor2/engInertia: 0.008 # in kg*m^3

prop2/propDiam: 1.3 # in m
prop2/nCoeffPoly/polyType: 0
prop2/nCoeffPoly/polyNo: 4
prop2/nCoeffPoly/coeffs: [0.0, -1.25, 19.73, -45.21, 28.81]
prop2/powerPoly/polyType: 0
prop2/powerPoly/polyNo: 3
prop2/powerPoly/coeffs: [0.0487, -0.1187, 0.1787, -0.1314]

battery/Rs: 0.0 # in Ohms
battery/Cells: 4 # number of LiPo cells