<?xml version="1.0"?>
<robot name="hexacopter" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="source" value="$(find last_letter_2)/config/param/models/hexacopter/mass.yaml" />
<xacro:property name="dictionary" value="${load_yaml(source)}"/>
<xacro:property name="body_mass" value="${dictionary['airframe/m']}"/>

<!-- body, airfoil sizes -->
<xacro:property name="body_s" value="1" />   

<!-- body link parameters x, y, z, mass-->
<xacro:property name="body_r" value="${body_s/2}" />
<xacro:property name="body_h" value="${body_s/8}" />
<xacro:property name="body_m" value="${body_mass}" />

    <link name="body_FLU">
        <visual>
        <origin rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${body_r}" length="${body_h}" />
            </geometry>
        </visual>

        <collision>
        <origin rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${body_r}" length="${body_h}" />
            </geometry>
        </collision>
        
        <inertial>
        <origin rpy="0 0 0"/>
            <mass value="${body_m}" />
             <inertia    ixx="${1/12*body_m*body_h*body_h+1/4*body_m*body_r*body_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*body_m*body_h*body_h+1/4*body_m*body_r*body_r}" 
                        izz="${1/2*body_m*body_r*body_r}" />
        </inertial> 

    </link>

---------------------------------------------------------- 6 quadcopter arms
<xacro:property name="arm_x" value="${2*body_s}" />
<xacro:property name="arm_y" value="${0.1*body_s}" />
<xacro:property name="arm_z" value="${0.1*body_s}" />
<xacro:property name="arm_m" value="${0.1*body_m}" />

    <link name="arm1">
        <visual>
        <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
               <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </visual>

        <collision>
        <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
               <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${arm_x/2} 0 0"/>
            <mass value="${arm_m}" />
            <inertia    ixx="${1/12*arm_m*(arm_y*arm_y+arm_z*arm_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*arm_m*(arm_x*arm_x+arm_z*arm_z)}" 
                        izz="${1/12*arm_m*(arm_x*arm_x+arm_y*arm_y)}" />
        </inertial> 
    </link>

    <joint name="body_FLU_to_arm1" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="body_FLU" />
        <child link="arm1" />
    </joint>
    
    <link name="arm2">
        <visual>
        <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
                <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
                <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${arm_x/2} 0 0"/>
            <mass value="${arm_m}" />
            <inertia    ixx="${1/12*arm_m*(arm_y*arm_y+arm_z*arm_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*arm_m*(arm_x*arm_x+arm_z*arm_z)}" 
                        izz="${1/12*arm_m*(arm_x*arm_x+arm_y*arm_y)}" />
        </inertial> 
    </link>

    <joint name="body_FLU_to_arm2" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 ${5/3*pi}"/>
        <parent link="body_FLU" />
        <child link="arm2" />
    </joint>

        <link name="arm3">
        <visual>
        <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
                <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
                <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${arm_x/2} 0 0"/>
            <mass value="${arm_m}" />
            <inertia    ixx="${1/12*arm_m*(arm_y*arm_y+arm_z*arm_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*arm_m*(arm_x*arm_x+arm_z*arm_z)}" 
                        izz="${1/12*arm_m*(arm_x*arm_x+arm_y*arm_y)}" />
        </inertial> 
    </link>

    <joint name="body_FLU_to_arm3" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 ${4/3*pi}"/>
        <parent link="body_FLU" />
        <child link="arm3" />
    </joint>

        <link name="arm4">
        <visual>
        <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
                <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
                <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${arm_x/2} 0 0"/>
            <mass value="${arm_m}" />
            <inertia    ixx="${1/12*arm_m*(arm_y*arm_y+arm_z*arm_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*arm_m*(arm_x*arm_x+arm_z*arm_z)}" 
                        izz="${1/12*arm_m*(arm_x*arm_x+arm_y*arm_y)}" />
        </inertial> 
    </link>

    <joint name="body_FLU_to_arm4" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <parent link="body_FLU" />
        <child link="arm4" />
    </joint>

     <link name="arm5">
        <visual>
        <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
                <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
                <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${arm_x/2} 0 0"/>
            <mass value="${arm_m}" />
            <inertia    ixx="${1/12*arm_m*(arm_y*arm_y+arm_z*arm_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*arm_m*(arm_x*arm_x+arm_z*arm_z)}" 
                        izz="${1/12*arm_m*(arm_x*arm_x+arm_y*arm_y)}" />
        </inertial> 
    </link>

    <joint name="body_FLU_to_arm5" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 ${2/3*pi}"/>
        <parent link="body_FLU" />
        <child link="arm5" />
    </joint>

     <link name="arm6">
        <visual>
        <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
                <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${arm_x/2} 0 0"/>
            <geometry>
                <box size="${arm_x} ${arm_y} ${arm_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${arm_x/2} 0 0"/>
            <mass value="${arm_m}" />
            <inertia    ixx="${1/12*arm_m*(arm_y*arm_y+arm_z*arm_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*arm_m*(arm_x*arm_x+arm_z*arm_z)}" 
                        izz="${1/12*arm_m*(arm_x*arm_x+arm_y*arm_y)}" />
        </inertial> 
    </link>

    <joint name="body_FLU_to_arm6" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 ${1/3*pi}"/>
        <parent link="body_FLU" />
        <child link="arm6" />
    </joint>

    -------------------------------------------------------------------------- motors


<xacro:property name="motor_r" value="${body_s/10}" />
<xacro:property name="motor_h" value="${body_s/10}" />
<xacro:property name="motor_m" value="${0.1*body_m}" />

<!-- only motor(Number_0f_Motor) acceptable name for motors -->
     <link name="motor1">
        <visual>
        <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${motor_m}" />
            <inertia    ixx="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" 
                        izz="${1/2*motor_m*motor_r*motor_r}" />
        </inertial> 
    </link>

    <joint name="arm1_to_motor1" type="revolute">
        <origin xyz="${arm_x-motor_r/2} 0 ${arm_z/2}" rpy="0 -1.57 0"/>
        <parent link="arm1" />
        <child link="motor1" />
        <limit effort="1000.0" velocity="0.5"/>  
    </joint>

     <link name="motor2">
        <visual>
        <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${motor_m}" />
            <inertia    ixx="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" 
                        izz="${1/2*motor_m*motor_r*motor_r}" />
        </inertial> 
    </link>

    <joint name="arm2_to_motor2" type="revolute">
        <origin xyz="${arm_x-motor_r/2} 0 ${arm_z/2}" rpy="0 -1.57 0"/>
        <parent link="arm2" />
        <child link="motor2" />
        <limit effort="1000.0" velocity="0.5"/>
    </joint>

     <link name="motor3">
        <visual>
        <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${motor_m}" />
            <inertia    ixx="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" 
                        izz="${1/2*motor_m*motor_r*motor_r}" />
        </inertial> 
    </link>

    <joint name="arm3_to_motor3" type="revolute">
        <origin xyz="${arm_x-motor_r/2} 0 ${arm_z/2}" rpy="0 -1.57 0"/>
        <parent link="arm3" />
        <child link="motor3" />
        <limit effort="1000.0" velocity="0.5"/>
    </joint>
         
     <link name="motor4">
        <visual>
        <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${motor_m}" />
            <inertia    ixx="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" 
                        izz="${1/2*motor_m*motor_r*motor_r}" />
        </inertial> 
    </link>

    <joint name="arm4_to_motor4" type="revolute">
        <origin xyz="${arm_x-motor_r/2} 0 ${arm_z/2}" rpy="0 -1.57 0"/>
        <parent link="arm4" />
        <child link="motor4" />
        <limit effort="1000.0" velocity="0.5"/>
    </joint>

         <link name="motor5">
        <visual>
        <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${motor_m}" />
            <inertia    ixx="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" 
                        izz="${1/2*motor_m*motor_r*motor_r}" />
        </inertial> 
    </link>

    <joint name="arm5_to_motor5" type="revolute">
        <origin xyz="${arm_x-motor_r/2} 0 ${arm_z/2}" rpy="0 -1.57 0"/>
        <parent link="arm5" />
        <child link="motor5" />
        <limit effort="1000.0" velocity="0.5"/>
    </joint>

         <link name="motor6">
        <visual>
        <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${motor_r}" length="${motor_h}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="${motor_r/2} 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${motor_m}" />
            <inertia    ixx="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*motor_m*motor_h*motor_h+1/4*motor_m*motor_r*motor_r}" 
                        izz="${1/2*motor_m*motor_r*motor_r}" />
        </inertial> 
    </link>

    <joint name="arm6_to_motor6" type="revolute">
        <origin xyz="${arm_x-motor_r/2} 0 ${arm_z/2}" rpy="0 -1.57 0"/>
        <parent link="arm6" />
        <child link="motor6" />
        <limit effort="1000.0" velocity="0.5"/>
    </joint>
 -------------------------------------------------------------- axles
<!-- arm link -->
<xacro:property name="axle_m" value="${body_m/20}" />
<xacro:property name="axle_r" value="${body_s/40}" />
<xacro:property name="axle_h" value="${body_s/40}" />
    
    <link name="axle1">
        <visual>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz="${axle_h/2} 0 0" />
            <mass value="${axle_m}" />
            <inertia    ixx="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" 
                        izz="${1/2*axle_m*axle_r*axle_r}" />
        </inertial>
    </link>

    <joint name="motor1_to_axle1" type="continuous">
        <origin xyz="${motor_r} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="motor1" />
        <child link="axle1" />
    </joint>

    <link name="axle2">
        <visual>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz="${axle_h/2} 0 0" />
            <mass value="${axle_m}" />
            <inertia    ixx="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" 
                        izz="${1/2*axle_m*axle_r*axle_r}" />
        </inertial>
    </link>

    <joint name="motor2_to_axle2" type="continuous">
        <origin xyz="${motor_r} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="motor2" />
        <child link="axle2" />
    </joint>

    <link name="axle3">
        <visual>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz="${axle_h/2} 0 0" />
            <mass value="${axle_m}" />
            <inertia    ixx="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" 
                        izz="${1/2*axle_m*axle_r*axle_r}" />
        </inertial>
    </link>

    <joint name="motor3_to_axle3" type="continuous">
        <origin xyz="${motor_r} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="motor3" />
        <child link="axle3" />
    </joint>

    <link name="axle4">
        <visual>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz="${axle_h/2} 0 0" />
            <mass value="${axle_m}" />
            <inertia    ixx="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" 
                        izz="${1/2*axle_m*axle_r*axle_r}" />
        </inertial>
    </link>

    <joint name="motor4_to_axle4" type="continuous">
        <origin xyz="${motor_r} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="motor4" />
        <child link="axle4" />
    </joint>

    <link name="axle5">
        <visual>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz="${axle_h/2} 0 0" />
            <mass value="${axle_m}" />
            <inertia    ixx="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" 
                        izz="${1/2*axle_m*axle_r*axle_r}" />
        </inertial>
    </link>

    <joint name="motor5_to_axle5" type="continuous">
        <origin xyz="${motor_r} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="motor5" />
        <child link="axle5" />
    </joint>

    <link name="axle6">
        <visual>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${axle_h/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${axle_r}" length="${axle_h}" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz="${axle_h/2} 0 0" />
            <mass value="${axle_m}" />
            <inertia    ixx="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*axle_m*axle_h*axle_h+1/4*axle_m*axle_r*axle_r}" 
                        izz="${1/2*axle_m*axle_r*axle_r}" />
        </inertial>
    </link>

    <joint name="motor6_to_axle6" type="continuous">
        <origin xyz="${motor_r} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="motor6" />
        <child link="axle6" />
    </joint>


  ------------------------------------------- propellers
<!-- propeller links -->
<xacro:property name="propeller_m" value="${body_m/20}" />
<xacro:property name="propeller_x" value="${1.5*body_s}" />
<xacro:property name="propeller_y" value="${body_s/10}" />   
<xacro:property name="propeller_z" value="${body_s/40}" />   

   <link name="prop1">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${propeller_m}" />
            <inertia    ixx="${1/12*propeller_m*(propeller_y*propeller_y+propeller_z*propeller_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*propeller_m*(propeller_x*propeller_x+propeller_z*propeller_z)}" 
                        izz="${1/12*propeller_m*(propeller_x*propeller_x+propeller_y*propeller_y)}" />
        </inertial> 
    </link>

    <joint name="axle1_to_prop1" type="fixed">
        <origin xyz="${axle_h} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="axle1" />
        <child link="prop1" />
    </joint>
    
   <link name="prop2">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${propeller_m}" />
            <inertia    ixx="${1/12*propeller_m*(propeller_y*propeller_y+propeller_z*propeller_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*propeller_m*(propeller_x*propeller_x+propeller_z*propeller_z)}" 
                        izz="${1/12*propeller_m*(propeller_x*propeller_x+propeller_y*propeller_y)}" />
        </inertial> 
    </link>

    <joint name="axle2_to_prop2" type="fixed">
        <origin xyz="${axle_h} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="axle2" />
        <child link="prop2" />
    </joint>
    
   <link name="prop3">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${propeller_m}" />
            <inertia    ixx="${1/12*propeller_m*(propeller_y*propeller_y+propeller_z*propeller_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*propeller_m*(propeller_x*propeller_x+propeller_z*propeller_z)}" 
                        izz="${1/12*propeller_m*(propeller_x*propeller_x+propeller_y*propeller_y)}" />
        </inertial> 
    </link>

    <joint name="axle3_to_prop3" type="fixed">
        <origin xyz="${axle_h} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="axle3" />
        <child link="prop3" />
    </joint>
    
   <link name="prop4">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${propeller_m}" />
            <inertia    ixx="${1/12*propeller_m*(propeller_y*propeller_y+propeller_z*propeller_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*propeller_m*(propeller_x*propeller_x+propeller_z*propeller_z)}" 
                        izz="${1/12*propeller_m*(propeller_x*propeller_x+propeller_y*propeller_y)}" />
        </inertial> 
    </link>

    <joint name="axle4_to_prop4" type="fixed">
        <origin xyz="${axle_h} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="axle4" />
        <child link="prop4" />
    </joint>
    
   <link name="prop5">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${propeller_m}" />
            <inertia    ixx="${1/12*propeller_m*(propeller_y*propeller_y+propeller_z*propeller_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*propeller_m*(propeller_x*propeller_x+propeller_z*propeller_z)}" 
                        izz="${1/12*propeller_m*(propeller_x*propeller_x+propeller_y*propeller_y)}" />
        </inertial> 
    </link>

    <joint name="axle5_to_prop5" type="fixed">
        <origin xyz="${axle_h} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="axle5" />
        <child link="prop5" />
    </joint>
    
   <link name="prop6">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${propeller_x} ${propeller_y} ${propeller_z}" />
            </geometry>
        </collision>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <mass value="${propeller_m}" />
            <inertia    ixx="${1/12*propeller_m*(propeller_y*propeller_y+propeller_z*propeller_z)}" ixy="0" ixz="0" iyz="0"
                        iyy="${1/12*propeller_m*(propeller_x*propeller_x+propeller_z*propeller_z)}" 
                        izz="${1/12*propeller_m*(propeller_x*propeller_x+propeller_y*propeller_y)}" />
        </inertial> 
    </link>

    <joint name="axle6_to_prop6" type="fixed">
        <origin xyz="${axle_h} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <parent link="axle6" />
        <child link="prop6" />
    </joint>
    
     
    --------------------------------------------------------------model plugins
    <gazebo>
    <plugin name="model_plugin" filename="libmodel_plugin.so"/>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
        <jointName>arm1_to_motor1, arm2_to_motor2, arm3_to_motor3,arm4_to_motor4,arm5_to_motor5,arm6_to_motor6,motor1_to_axle1,motor2_to_axle2,motor3_to_axle3,motor4_to_axle4,motor5_to_axle5,motor6_to_axle6 </jointName>
        <robotNamespace>last_letter_2</robotNamespace>
        <updateRate>0</updateRate>
    </plugin>
  </gazebo>
</robot>
