# Basic model Characteristics

#In case of multirotor
/model/b: 0.3  # thrust constant [Ns^2]
/model/l: 2     # motor distance to center of gravity
/model/d: 0.6   # drag factor [Nms]

# hexacopter matrix  << b,    b,           b,          b,    b,          b,            //thrust row 
#                       0,   -b*l*1.73/2, -b*l*1.73/2, 0,    b*l*1.73/2, b*l*1.73/2,   //roll row
#                       b*l,  b*l/2,      -b*l/2,     -b*l, -b*l/2,      b*l/2,        //pitch row
#                      -d,    d,          -d,          d,   -d,          d;            //yaw row