# Motor Parameters
# Motor types: 0 No motor, 1 generic Engine, 2 electric Engine

nMotors: 6

#motor 1
motor1/motorType: 1
motor1/rotationDir: -1.0
motor1/input_chan: 0

#features for generic Engine
motor1/s_prop: 0.2027
motor1/k_motor: 80
motor1/k_t_p: 1.0   #constant determined by experiment
motor1/k_omega: 20.0
motor1/c_prop: 1.0

#motor 2
motor2/motorType: 1
motor2/rotationDir: 1.0
motor2/input_chan: 1

#features for generic Engine
motor2/s_prop: 0.2027
motor2/k_motor: 80
motor2/k_t_p: 1.0
motor2/k_omega: 20.0
motor2/c_prop: 1.0

#motor 3
motor3/motorType: 1
motor3/rotationDir: -1.0
motor3/input_chan: 2

#features for generic Engine
motor3/s_prop: 0.2027
motor3/k_motor: 80
motor3/k_t_p: 1.0
motor3/k_omega: 20.0
motor3/c_prop: 1.0

#motor 4
motor4/motorType: 1
motor4/rotationDir: 1.0
motor4/input_chan: 3

#features for generic Engine
motor4/s_prop: 0.2027
motor4/k_motor: 80
motor4/k_t_p: 1.0
motor4/k_omega: 20.0
motor4/c_prop: 1.0

#motor 5
motor5/motorType: 1
motor5/rotationDir: -1.0
motor5/input_chan: 4


#features for generic Engine
motor5/s_prop: 0.2027
motor5/k_motor: 80
motor5/k_t_p: 1.0
motor5/k_omega: 20.0
motor5/c_prop: 1.0

#motor 6
motor6/motorType: 1
motor6/rotationDir: 1.0
motor6/input_chan: 5

#features for generic Engine
motor6/s_prop: 0.2027
motor6/k_motor: 80
motor6/k_t_p: 1.0
motor6/k_omega: 20.0
motor6/c_prop: 1.0