# Basic model Characteristics

#In case of multirotor
/model/b: 0.25  # thrust constant [Ns^2]
/model/l: 2     # motor distance to center of gravity
/model/d: 0.6   # drag factor [Nms]
/model/k: 0.6   # 

# quadcopter matrix << b,     b,      b,      b,      //thrust row
#                      0,    -l * k,  0,      l * k,  //roll row
#                      l * k, 0,     -l * k,  0,      //pitch row
#                     -d,     d,     -d,      d;      //yaw row