# Airframe Propulsion Parameters
# Motor types: 0 No motor, 1 generic Engine

nMotors: 4


motor1/motorType: 1
motor1/rotationDir: -1.0
motor1/input_chan: 0

#features for generic Engine
motor1/s_prop: 0.2027
motor1/k_motor: 80
motor1/k_t_p: 1.0   #constant determined by experiment
motor1/k_omega: 20.0
motor1/c_prop: 1.0

#motor 2 charachteristics
motor2/motorType: 1
motor2/rotationDir: 1.0
motor2/input_chan: 1

#features for generic Engine
motor2/s_prop: 0.2027
motor2/k_motor: 80
motor2/k_t_p: 1.0
motor2/k_omega: 20.0
motor2/c_prop: 1.0

#motor 3 charachteristics
motor3/motorType: 1
motor3/rotationDir: -1.0
motor3/input_chan: 2

#features for generic Engine
motor3/s_prop: 0.2027
motor3/k_motor: 80
motor3/k_t_p: 1.0
motor3/k_omega: 20.0
motor3/c_prop: 1.0

#motor 3 charachteristics
motor4/motorType: 1
motor4/rotationDir: 1.0
motor4/input_chan: 3

#features for generic Engine
motor4/s_prop: 0.2027
motor4/k_motor: 80
motor4/k_t_p: 1.0
motor4/k_omega: 20.0
motor4/c_prop: 1.0
