#Parameters for plane_3wing_2motor airframe
#All units are in S.I. unless otherwise stated

#Initial State
#Caution. Always in doulbe style (with dot)
init/position: [0.0, 0.0, 10.0] #NWU frame
init/orientation:  [0.0, 0.0, 0.0] #NWU frame as RPY
init/velLin:   [50.0, 0.0, 0.0] #body frame
init/velAng: [0.0, 0.0, 0.0] #body frame