#airfoil Aerodynamic Parameters
#aerodynamicsType: 0:NoAerodynamics, 1:StdLinearAero 2:HCUAVAero
nWings: 3

aileron: 0  #Number of relative channel from joystick
elevator: 1
rudder: 3
thrust: 2

airfoil1/chanGimbal: -1
airfoil1/gimbalAngle_max: 0.0

airfoil1/CGOffset: [-0.02, 0.00, -0.05] # vector from CG to CoL
airfoil1/mountOrientation: [0.0, 0.0, 0.0] # Euler rotations from body axes to propeller normal plane. Gimbal rotation axis should be in z-axis.
airfoil1/gimbalAxis: 0
airfoil1/aerodynamicsType: 1
airfoil1/s: 0.45   #wing surface = b*c
airfoil1/b: 1.88   #wingspan
airfoil1/c: 0.24   #wing mean cord

airfoil1/c_lift_0: 0.56 
airfoil1/c_lift_deltae: 0.0
airfoil1/c_lift_a: 6.9
airfoil1/c_lift_q: 0
airfoil1/mcoeff: 50
airfoil1/oswald: 0.9
airfoil1/alpha_stall: 0.4712
airfoil1/c_drag_q: 0.0
airfoil1/c_drag_deltae: 0.0
airfoil1/c_drag_p: 0.0437
airfoil1/c_drag_0: 0.03
airfoil1/c_drag_a: 0.3
airfoil1/c_y_0: 0
airfoil1/c_y_b: -0.98
airfoil1/c_y_p: 0
airfoil1/c_y_r: 0
airfoil1/c_y_deltaa: 0
airfoil1/c_y_deltar: -0.2 #opposite sign than c_n_deltar

airfoil1/c_l_0: 0
airfoil1/c_l_p: -1.0
airfoil1/c_l_b: -0.12
airfoil1/c_l_r: 0.14
airfoil1/c_l_deltaa: 0.05 #0.25
airfoil1/c_l_deltar: -0.037
airfoil1/c_m_0: 0.045
airfoil1/c_m_a: -0.7
airfoil1/c_m_q: -20
airfoil1/c_m_deltae: 1.0
airfoil1/c_n_0: 0
airfoil1/c_n_b: 0.25
airfoil1/c_n_p: 0.022
airfoil1/c_n_r: -1
airfoil1/c_n_deltaa: 0.00
airfoil1/c_n_deltar: 0.1 #opposite sign than c_y_deltar

airfoil1/deltax_max: 0.3491  #max deflections in radians
airfoil1/deltay_max: 0
airfoil1/deltaz_max: 0

#0 if airfoil is not affect for move (relative to airfoil), else 1,2,3 for which of the input signals the airfoil listens to
#0-nothing, 1-aileron, 2-elevator, 3-rudder  (input signals)
airfoil1/roll_move: 1     #airfoil1 affects only roll and listens to aileron signal
airfoil1/pitch_move: 0    #airfoil1 not affects pitch move
airfoil1/yaw_move: 0      #airfoil1 not affects yaw move

# airfoil 2
airfoil2/chanGimbal: -1
airfoil2/gimbalAngle_max: 0.0

airfoil2/CGOffset: [-0.02, 0.00, -0.05] # vector from CG to CoL
airfoil2/mountOrientation: [0.0, 0.0, 0.0] # Euler rotations from body axes to propeller normal plane. Gimbal rotation axis should be in z-axis.
airfoil2/gimbalAxis: 0
airfoil2/aerodynamicsType: 1
airfoil2/s: 0.12   #wing surface = b*c
airfoil2/b: 0.5   #wingspan
airfoil2/c: 0.24   #wing mean cord

airfoil2/c_lift_0: 0.56 #0.56
airfoil2/c_lift_deltae: -1.0
airfoil2/c_lift_a: 6.9
airfoil2/c_lift_q: 0
airfoil2/mcoeff: 50
airfoil2/oswald: 0.9
airfoil2/alpha_stall: 0.4712
airfoil2/c_drag_q: 0.0
airfoil2/c_drag_deltae: 0.0
airfoil2/c_drag_p: 0.0437
airfoil2/c_drag_0: 0.03
airfoil2/c_drag_a: 0.3
airfoil2/c_y_0: 0
airfoil2/c_y_b: -0.98
airfoil2/c_y_p: 0
airfoil2/c_y_r: 0
airfoil2/c_y_deltaa: 0
airfoil2/c_y_deltar: 0 #opposite sign than c_n_deltar

airfoil2/c_l_0: 0
airfoil2/c_l_p: -1.0
airfoil2/c_l_b: -0.12
airfoil2/c_l_r: 0.14
airfoil2/c_l_deltaa: 0.25
airfoil2/c_l_deltar: -0.037
airfoil2/c_m_0: 0.045
airfoil2/c_m_a: -0.7
airfoil2/c_m_q: -20
airfoil2/c_m_deltae: 1.0
airfoil2/c_n_0: 0
airfoil2/c_n_b: 0.25
airfoil2/c_n_p: 0.022
airfoil2/c_n_r: -1
airfoil2/c_n_deltaa: 0.00
airfoil2/c_n_deltar: 0.1 #opposite sign than c_y_deltar

airfoil2/deltax_max: 0       #max deflections in radians
airfoil2/deltay_max: 0.3491
airfoil2/deltaz_max: 0

#0 if airfoil is not affect for move (relative to airfoil), else 1,2,3 for which of the input signals the airfoil listens to
airfoil2/roll_move: 0   #0-nothing, 1-aileron, 2-elevator, 3-rudder  (input signals)
airfoil2/pitch_move: 2
airfoil2/yaw_move: 0

# airfoil 3
airfoil3/chanGimbal: -1
airfoil3/gimbalAngle_max: 0.0

airfoil3/CGOffset: [-0.02, 0.00, -0.05] # vector from CG to CoL
airfoil3/mountOrientation: [0.0, 0.0, 0.0] # Euler rotations from body axes to propeller normal plane. Gimbal rotation axis should be in z-axis.
airfoil3/gimbalAxis: 0
airfoil3/aerodynamicsType: 1
airfoil3/s: 0.48   #wing surface = b*c
airfoil3/b: 2   #wingspan
airfoil3/c: 0.24   #wing mean cord

airfoil3/c_lift_0: 0
airfoil3/c_lift_deltae: -2.0
airfoil3/c_lift_a: 6.9
airfoil3/c_lift_q: 0
airfoil3/mcoeff: 50
airfoil3/oswald: 0.9
airfoil3/alpha_stall: 0.4712
airfoil3/c_drag_q: 0.0
airfoil3/c_drag_deltae: 0.0
airfoil3/c_drag_p: 0.0437
airfoil3/c_drag_0: 0.03
airfoil3/c_drag_a: 0.3
airfoil3/c_y_0: 0
airfoil3/c_y_b: 0
airfoil3/c_y_p: 0
airfoil3/c_y_r: 0
airfoil3/c_y_deltaa: 0
airfoil3/c_y_deltar: -0.2 #opposite sign than c_n_deltar

airfoil3/c_l_0: 0
airfoil3/c_l_p: 0
airfoil3/c_l_b: 0
airfoil3/c_l_r: 0
airfoil3/c_l_deltaa: 0
airfoil3/c_l_deltar: 0
airfoil3/c_m_0: 0
airfoil3/c_m_a: 0
airfoil3/c_m_q: 0
airfoil3/c_m_deltae: 0
airfoil3/c_n_0: 0
airfoil3/c_n_b: 0
airfoil3/c_n_p: 0
airfoil3/c_n_r: 0
airfoil3/c_n_deltaa: 0.00
airfoil3/c_n_deltar: 0 #opposite sign than c_y_deltar

airfoil3/deltax_max: 0       #max deflections in radians
airfoil3/deltay_max: 0.3491
airfoil3/deltaz_max: 0

#0 if airfoil is not affect the move (relative to airfoil), else 1,2,3 for which of the input signals the airfoil listens to
airfoil3/roll_move: 0   #0-nothing, 1-aileron, 2-elevator, 3-rudder  (input signals)
airfoil3/pitch_move: 3
airfoil3/yaw_move: 0
