# Airframe Propulsion Parameters
# Motor types: 0 No motor, 1 generic Engine

nMotors: 1
motor1/motorType: 1
motor1/rotationDir: 1.0

#features for generic Engine
motor1/s_prop: 0.19625
motor1/c_prop: 1.0
motor1/k_motor: 55
motor1/k_t_p: 0.0
motor1/k_omega: 20.0

