#Generic Environment Parameters
/environment/rho: 1.2250 #Air density in kg/m^3
/environment/Rd: 287.05307  #Gas constant for dry air, J/kg K
/environment/L0: -6.5  #Temperature lapse rate, at sea level deg K/km
/environment/gravity: -9.81 #gravity at sea level

#Parameters for the atmoshpere model
/environment/groundTemp: 25 #in Celsius
/environment/groundPres: 1013.25 #in mBar

#Parameters for the wind model
/environment/windRef: 1.0 #in m/s
/environment/windRefAlt: 10.0 #in m
/environment/windDir: 90.0 #in degrees
/environment/surfSmooth: 0.28 #rural environment
/environment/Dryden/Lu: 533.0
/environment/Dryden/Lw: 533.0
/environment/Dryden/sigmau: 155.0
/environment/Dryden/sigmaw: 155.0
/environment/Dryden/use: 0.0 #produce turbulence 0/1
