#Physics Parameters

#Simulation calculation rate 
/updatePhysics/simRate: 500

#Simulation time-step
/updatePhysics/deltaT: 0.002

# realTimeFactor = simRate * deltaT
# For real time simulation simRate * deltaT = 1