#Global Miscellaneous Parameters

#Simulation calculation rate (frame rate)
/world/simRate: 500

#Simulation time-step
/world/deltaT: 0.002

#Simulation time controls
# 0 : default real-time simulation clock
# 1 : controls-triggered simulation clock
# 2 : free-spinning simulation clock
#/world/timeControls: 0

#/world/integratorType: 0