# Airframe Propulsion Parameters
# Motor types: 0 No motor, 1 generic Engine, 2 Piston engine, 3 Electric Engine
# Polynomial types: 0 1D, 1 2D, 2 cubic spline

nMotors: 4

motor1/enable: 1  #1 if motor is in use, 0 if out of use
motor1/chanMotor: 0

motor1/CGOffset: [-0.25, 0.0, -0.13] # location offset of the motor mount relative to CG
motor1/mountOrientation: [0.0, 0.0, 0.0] # Euler rotations from body axes to propeller normal plane. Gimbal rotation axis should be in z-axis.
motor1/chanGimbal: -1
motor1/gimbalAngle_max: 0.0

motor1/rotationDir: -1.0

motor1/motorType: 1

#features for generic Engine
motor1/s_prop: 0.2027
motor1/k_motor: 80
motor1/k_t_p: 1.0   #constant determined by experiment
motor1/k_omega: 20.0
motor1/c_prop: 1.0

#motor 2 charachteristics
motor2/enable: 1  #1 if motor is in use, 0 if out of use
motor2/chanMotor: 1

motor2/CGOffset: [-0.25, 0.0, -0.13] # location offset of the motor mount relative to CG
motor2/mountOrientation: [0.0, 0.0, 0.0] # Euler rotations from body axes to propeller normal plane. Gimbal rotation axis should be in z-axis.
motor2/chanGimbal: -1
motor2/gimbalAngle_max: 0.0

motor2/rotationDir: 1.0

motor2/motorType: 1

#features for generic Engine
motor2/s_prop: 0.2027
motor2/k_motor: 80
motor2/k_t_p: 1.0
motor2/k_omega: 20.0
motor2/c_prop: 1.0

#motor 3 charachteristics
motor3/enable: 1  #1 if motor is in use, 0 if out of use
motor3/chanMotor: 2

motor3/CGOffset: [-0.25, 0.0, -0.13] # location offset of the motor mount relative to CG
motor3/mountOrientation: [0.0, 0.0, 0.0] # Euler rotations from body axes to propeller normal plane. Gimbal rotation axis should be in z-axis.
motor3/chanGimbal: -1
motor3/gimbalAngle_max: 0.0

motor3/rotationDir: -1.0

motor3/motorType: 1

#features for generic Engine
motor3/s_prop: 0.2027
motor3/k_motor: 80
motor3/k_t_p: 1.0
motor3/k_omega: 20.0
motor3/c_prop: 1.0

#motor 3 charachteristics
motor4/enable: 1  #1 if motor is in use, 0 if out of use
motor4/chanMotor: 3

motor4/CGOffset: [-0.25, 0.0, -0.13] # location offset of the motor mount relative to CG
motor4/mountOrientation: [0.0, 0.0, 0.0] # Euler rotations from body axes to propeller normal plane. Gimbal rotation axis should be in z-axis.
motor4/chanGimbal: -1
motor4/gimbalAngle_max: 0.0

motor4/rotationDir: 1.0

motor4/motorType: 1

#features for generic Engine
motor4/s_prop: 0.2027
motor4/k_motor: 80
motor4/k_t_p: 1.0
motor4/k_omega: 20.0
motor4/c_prop: 1.0
